#
# Configuration File
#

# Enable additional diagnostics
verbose: true
profile: true

# Information for compile
exclude:
  - "CNAME"
  - "LICENSE"
  - "README.md"
  - "DEVELOPMENT.md"
  - "ATTRIBUTIONS.md"
  - "_posts/README.md"
  - "*.js"
  - "*.json"
  - "assets/images/favicon/*.webmanifest"
  - "assets/images/favicon/*.md"
  - "assets/images/favicon/*.html"
  - "assets/images/favicon/*.xml"

# Plugins
plugins:
  - jekyll-sitemap

# Sass configuration
sass:
  sass_dir: _scss

# Information for deploy
baseurl: ""

# the base hostname & protocol for your site
url: "https://cardilloscreations.com"

assets_path:  assets
css_path:     assets/css
images_path:  assets/images

##
## HEADER INFORMATION
##

# This is the site title
title: Cardillo's Creations
# This is the site description - must be between 25 and 160 characters for Bing SEO
description: >
  Cardillo's Creations makes limited edition gifts and custom wares.
  Every item is designed and handmade with care and attention to detail.


# Website language
lang: en-US
# Header Title
header-title: Cardillo's Creations
# Header Tagline
header-tagline: Unique Gifts and Custom Wares

# The general contact default email address
email: hello@cardilloscreations.com

##
## Global Links
##
youtube: "https://www.youtube.com/@CardillosCreations"
facebook: "https://www.facebook.com/CardillosCreations/"
instagram: "https://www.instagram.com/cardilloscreations/"
twitter: "https://twitter.com/CardilloCreates"
tiktok: "https://www.tiktok.com/@cardilloscreations"
etsy: "https://www.etsy.com/shop/CardillosCreations"

##
## Global Images
##
default-image: default.webp
link-icon: icons/link.svg
email-icon: icons/email.svg
shop-icon: icons/shop.svg
facebook-icon: icons/facebook.svg
instagram-icon: icons/instagram.svg
twitterx-icon: icons/twitterx.svg
tiktok-icon: icons/tiktok.svg
youtube-icon: icons/youtube.svg
linkedin-icon: icons/linkedin.svg
pinterest-icon: icons/pinterest.svg
amazon-icon: icons/amazon.svg

##
## Footer
##
footer-description: Find us on social media.
footer-copyright-text: Cardillo's Creations, LLC
footer-copyright-year: 2024
