#
# Sera - OnePage Jekyll Theme
# Configuration File
#

# Information for compile
exclude: ["Gemfile", "CNAME", "LICENSE", "README.md", "AUTHORING.md"]

# Sass configuration
sass:
  sass_dir: _scss

# Information for deploy
baseurl: ""

# the base hostname & protocol for your site
url: "https://cardilloscreations.com"

####################################
######   Optional Features    ######
####################################
smooth-scroll: false

####################################
###########   Plugins    ###########
####################################
plugins:
  - jekyll-archives

jekyll-archives:
  enabled:
    - categories
    - tags
  layout: "archive"
  permalinks:
    category: "/category/:name/"
    tag: "/tag/:name/"

#######################################################
#######################################################
###############   HEADER INFORMATION   ###############
#######################################################
#######################################################

# This is your site title
title: Cardillo's Creations
# Website language
lang: en-US
# Header Title
header-title: Cardillo's Creations
# Header Tagline
header-tagline: Ray Cardillo's Creative Pursuits

#
# This is your email adress, contact from send here all emails from contact section
# IMPORTANT: you can modify contact form from this static template, but now works contact form works with a free external server
# To configure this contact form, first please send a fictive email afeter you enter below your email and verify that :)
#
email: hello@cardilloscreations.com

####################################
######  Global Social Links   ######
####################################
youtube: "https://www.youtube.com/channel/UC0HU7g_ZH-sXbmjlW4nXgQg"
facebook: "https://www.facebook.com/CardillosCreations/"
instagram: "https://www.instagram.com/cardilloscreations/"
twitter: "https://twitter.com/CardilloCreates"
tiktok: "https://www.tiktok.com/@cardilloscreations"

#########################
######   Widgets   ######
#########################

#####################################
#############   About   #############
#####################################
about-title: About Us
about-description-short: Cardillo's Creations is owned by Ray Cardillo.
about-description-long: >
  This was once my mobile app website but I have removed my mobile applications
  from the app stores so I can focus on other creative pursuits.
  See my brand portfolio below to learn more.

#####################################
############  Portfolio  ############
#####################################
portfolio-title: Portfolio
portfolio-description: I am now focusing mainly on content creation and artistic interests.

#
# Portfolio Grid
#
portfolio-categories:
  [YouTube, Artistic]
portfolio:
  # Portfolio Item
  - title: L<span class="thin">ong</span> T<span class="thin">ooth</span> G<span class="thin">amer</span>
    categories: [YouTube]
    image: long-tooth-gamer-portfolio-image.jpg
    url: "https://longtoothgamer.com"
    ext-icon: "fa-brands fa-youtube"
    ext-url: "https://www.youtube.com/channel/UC8nJI40ZJ2C682oAsB16gCA"

  # Portfolio Item
  - title: L<span class="thin">isa</span> L<span class="thin">affs</span>
    categories: [YouTube]
    image: lisa-laffs-portfolio-image.jpg
    url: "https://lisalaffs.com"
    ext-icon: "fa-brands fa-youtube"
    ext-url: "https://www.youtube.com/channel/UCOGZnusrYFnZ_L4QyHx0p-Q"

  # Portfolio Item
  - title: C<span class="thin">ardillo's</span> A<span class="thin">rt</span>
    categories: [Artistic]
    image: cardillos-art-portfolio-image.jpg
    url: "https://cardillos.art"
    ext-icon: "fa-brands fa-youtube"
    ext-url: "https://www.youtube.com/channel/UCt8wFoYrllXNbRUNZHflX_Q"

  # Portfolio Item
  - title: M<span class="thin">r</span> M<span class="thin">ighty's</span> F<span class="thin">ine</span> D<span class="thin">esigns</span>
    categories: [Artistic]
    image: mmfd-portfolio-image.jpg
    url: "https://mrmightysfinedesigns.com"
    ext-icon: "fa-solid fa-cart-shopping"
    ext-url: "https://www.etsy.com/shop/MrMightysFineDesigns"

#####################################
#############   Footer   ############
#####################################
footer-description: Find Cardillo's Creations on all of your favorite sites.
footer-copyright-text: Cardillo's Creations, LLC
footer-copyright-year: 2021
